### ISSUE TITLE
Inaccuracies

### ISSUE THREAD

**Issue by mark-wade** [ilyankou/passport-index-dataset#10]
UK passport holders going to Australia, Canada, New Zealand, and United States is listed as VOA but an ETA is required is required for all of these countries.

**Comment by ilyankou** [comment]
Hi @mark-wade 

I've updated the scraper to work with the new version of PassportIndex website, and it looks like the UK passport requirements are correct now (although 3 of 4 countries you mentioned have a `covid ban` for UK visitors). I grouped eVisas/eTAs/eVisitors (specific to Australia) under the `e-visa` group. Thanks for spotting this!
