### ISSUE TITLE
Script problem

### ISSUE THREAD

**Issue by andredutoit38** [ilyankou/passport-index-dataset#11]
Firstly, thanks for this handy source of data. 
I've tried to run the to Jupyter notebook (using Jupyter Notebook (anaconda3)  but it produces an error  early on:

****---> 14 data = js2py.eval_js(script)
NameError: name 'script' is not defined****

I would love to update the dataset myself but it seems aomewhat above my skill level to figure out.
Any advice?

**Comment by ilyankou** [comment]
Hi @andredutoit38 

It looks like they redesigned the page entirely, and removed JS scripts and arrays with data. I will update & publish my scraper in the next few days, but I was able to write a quick scraper to get today's data (see CSV attached). Hope this helps!

🗂 [2020-11-17.csv.zip](https://github.com/ilyankou/passport-index-dataset/files/5556498/2020-11-17.csv.zip)

**Comment by andredutoit38** [comment]
Thank you! It sort-of helps :-) Looking forward to see if you can get the scraper up and running again. The tidy-iso2.csv is the format which works best and the way yoy simplified content with VF, VR and days was just perfect.

**Comment by ilyankou** [comment]
Hi @andredutoit38 

I've updated the files with the new scraper. I introduced new categories (`no admission` and `covid ban`) and changed the old ones. The overall idea (6 files, 3 tidy and 3 matrix, iso2, iso3, and full names) is the same. See README for more information. Hope this is useful!

**Comment by andredutoit38** [comment]
Fantastic thank you so much! I've tested the notebook and everything looks good.
