### ISSUE TITLE
Update.ipynb throws JSONDecodeError

### ISSUE THREAD

**Issue by tomasbal** [ilyankou/passport-index-dataset#14]
Hi, 

this is the response when trying to run ipynb:

`<Response [200]>

---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
/var/folders/kg/bwrvz9nd783cq_myf1qj22mw0000gn/T/ipykernel_30597/458468694.py in <module>
      1 print(result_raw)
----> 2 result = json.loads( result_raw.text )
      3 obj = {}
      4 
      5 for passport in result:

/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    344             parse_int is None and parse_float is None and
    345             parse_constant is None and object_pairs_hook is None and not kw):
--> 346         return _default_decoder.decode(s)
    347     if cls is None:
    348         cls = JSONDecoder

/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py in decode(self, s, _w)
    335 
    336         """
--> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338         end = _w(s, end).end()
    339         if end != len(s):

/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py in raw_decode(self, s, idx)
    353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

`

**Comment by ilyankou** [comment]
Hi @tomasbal,

Not sure what's going on there, but here's the most recent run (9 August 2021): https://github.com/ilyankou/passport-index-dataset/releases/tag/v2021.08.09

**Comment by tomasbal** [comment]
Hi @ilyankou,

I've updated the api function like this and it works now.

```
url = "https://www.passportindex.org/incl/compare2.php"

payload = "compare=1"
headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0",
    "Accept": "*/*",
    "Accept-Language": "en-US,en;q=0.5",
    "Referer": "https://www.passportindex.org/comparebyPassport.php",
    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
    "X-Requested-With": "XMLHttpRequest",
    "Pragma": "no-cache",
    "Cache-Control": "no-cache",
    "Origin": "https://www.passportindex.org",
    "Connection": "keep-alive",
    "Sec-Fetch-Dest": "empty",
    "Sec-Fetch-Mode": "cors",
    "Sec-Fetch-Site": "same-origin",
    "TE": "trailers"
}

result_raw = requests.request("POST", url, data=payload, headers=headers)

```

I'm marking this problem as closed.
