### ISSUE TITLE
Notebook not working after update?

### ISSUE THREAD

**Issue by andredutoit38** [ilyankou/passport-index-dataset#15]
Hi again and thank you for the update. 
Perhaps something changed in the script that I missed, but after the update I cannot run the Jupyter notebook anymore to update datasets. The previous notebook also does not work. Does the notebook run correctly fir you? Appreciate your help.

**Comment by ilyankou** [comment]
It does run for me, but see this https://github.com/ilyankou/passport-index-dataset/issues/14, maybe that helps?

**Comment by andredutoit38** [comment]
Thank you - I've made the same change and that solved my problem.
