### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by bonbonio** [ilyankou/passport-index-dataset#18]
Hi, 

I love this so thank you so much, but I think the format used to be a bit more elegant...

Visa required was VR, Visa on arrival was VOA, so you could use CB for Covid Ban... do you remember this? Wondering why it was changed!

**Comment by ilyankou** [comment]
Hi @bonbonio 

Thank you. My thinking re the format was that:
* it's fairly straightforward to change numeric values (=days) to `visa-free`/`VF` labels (as opposed to guess the duration of VFs, which would be impossible without an extra dataset), and
* full labels, such as `visa on arrival`, are easier to interpret than abbreviations (`VOA`), for which you'd need a crosswalk to consult.

Changing these back to the way they used to be should be relatively easy in Excel/Google Sheets using formulas, and even easier in R/Python, so I'm tempted to keep these as is, at least for now.

**Comment by bonbonio** [comment]
I understood that any with a duration (number) would be the Visa free
period…

I just found the old constant values were easier to work with but I could
scoot the replacements i guess, I just think it was neater.

Thanks though, it’s a great data set!
-- 
Regards,

Darryl Haydn Jones

Managing Director | Bonbon Group Ltd
