### ISSUE TITLE
Question on how to understand datasets with "covid ban".

### ISSUE THREAD

**Issue by nassarhuda** [ilyankou/passport-index-dataset#19]
I just picked this line from one of the datasets:
`Latvia,Vietnam,covid ban`
...
Does this mean that people with a Latvian passport are not allowed to enter Vietnam? Or does it mean that someone coming from Latvia (with possibly a different passport, a non-Latvian passport) is not allowed to enter Vietnam?

I see the header is `Passport,Destination,Requirement`, but it's confusing because I thought the premise of covid bans was based on where the person was coming from rather than what passport they hold.

Thank you!

**Comment by ilyankou** [comment]
Hi Huda,

This is a great question and my natural guess would be the latter: I'd say broadly it affects people coming from Latvia to Vietnam with any passport (other than the Vietnamese, likely). There surely are exceptions, such as if a country decided to stop issuing visas to certain nationalities, which may affect passport holders directly.

IATA has a Covid-specific map which can be useful: https://www.iatatravelcentre.com/world.php

Ilya

**Comment by nassarhuda** [comment]
Makes sense, thanks for the reply!
