### ISSUE TITLE
Data seems wrong

### ISSUE THREAD

**Issue by wcil** [ilyankou/passport-index-dataset#2]
Hi, was just looking at the data compared to Passport Index and it seems wildly different for certain countries. Looking at Angola for instance, the only countries that can travel visa free to Angola are:

MZ
NA
ZA

What's up on Passport Index is very different - Singapore passport can go to Angola without a visa.

Any ideas? Thank

**Comment by ilyankou** [comment]
@wcil well spotted! Indeed some columns seem off. I will re-run the script and see what's up in the next few days.

**Comment by wcil** [comment]
Thanks for the quick reply - great stuff :)

**Comment by ilyankou** [comment]
Hey @wcil,

I ran the script today (June 01, 2018) with the most up-to-date data, and it seems to resolve the issue for Angola. Now there are 8 countries in the list, including Singapore -- and Wiki confirms those are indeed the countries that can travel to Angola visa free (see here https://en.wikipedia.org/wiki/Visa_policy_of_Angola). Also, according to Wiki, a bunch of countries were granted online-pre-visa entry to Angola in March 2018, yet Passport Index does not list them - perhaps all the paperwork to obtain it ("proof of accommodation and subsistence means, a return ticket and the international certificate of vaccination") makes it too cumbersome.

Please let me know if you stop any other discrepancies and I will look into them!

**Comment by wcil** [comment]
Thanks, that looks great now :)
