### ISSUE TITLE
No data returned from "Get data from PassportIndex" Step

### ISSUE THREAD

**Issue by spacemunkey77** [ilyankou/passport-index-dataset#22]
When I run the Jupyter Notebook Update.ipynb and get to the "Get Passport Data" step it is returning zero data. Then when I get to the next step it says:

---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
Cell In[8], line 1
----> 1 result = json.loads( result_raw.text )
      2 obj = {}
      4 for passport in result:
      5     
      6     # Fix ISO-2 codes

File /opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py:346, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    341     s = s.decode(detect_encoding(s), 'surrogatepass')
    343 if (cls is None and object_hook is None and
    344         parse_int is None and parse_float is None and
    345         parse_constant is None and object_pairs_hook is None and not kw):
--> 346     return _default_decoder.decode(s)
    347 if cls is None:
    348     cls = JSONDecoder

File /opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py:337, in JSONDecoder.decode(self, s, _w)
    332 def decode(self, s, _w=WHITESPACE.match):
    333     """Return the Python representation of ``s`` (a ``str`` instance
    334     containing a JSON document).
    335 
    336     """
--> 337     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338     end = _w(s, end).end()
    339     if end != len(s):

File /opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
    353     obj, end = self.scan_once(s, idx)
    354 except StopIteration as err:
--> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
    356 return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ilyankou** [comment]
Hi @spacemunkey77 

They seem to have upgraded their API. See updated Notebook and let me know if you can run it!

**Comment by spacemunkey77** [comment]
> Hi @spacemunkey77
> 
> They seem to have upgraded their API. See updated Notebook and let me know if you can run it!

I got this to work by adding/updating the following functions and code.

`from bs4 import BeautifulSoup
 import re

   def fix_iso2(x):
    o = {
        'UK': 'GB',
        'RK': 'XK'
    }
    return o[x] if x in o else x

def get_csrf_token():
    
    url = "https://www.passportindex.org/comparebyPassport.php"
    
    try:
        
        # Send a GET request to the URL
        response = session.get(url)

        # Check if the request was successful
        if response.status_code == 200:
            # Parse the HTML content
            soup = BeautifulSoup(response.text, 'html.parser')
            
            # Find all <script> tags
            script_tags = soup.find_all('script')
            
            # Initialize csrf_token variable
            csrf_token = None
            
            # Loop through each <script> tag to find the csrf_token
            for script in script_tags:
                # Use a regular expression to search for csrf_token
                if script.string:
                    match = re.search(r'csrf_token\s*=\s*"(.*?)"', script.string)
                    if match:
                        csrf_token = match.group(1)
                        break
            
            if csrf_token:
                return csrf_token
            else:
                return "CSRF Token not found."
        else:
            return f"Failed to fetch the URL. Status code: {response.status_code}"
    except Exception as e:
        return f"An error occurred: {e}"

# URL to fetch the source code from


# Get the CSRF token
csrf_token = get_csrf_token()
print(f"CSRF Token: {csrf_token}")

def get_data(country_code):

    time.sleep(0.2) # Do not overload the server

    return session.post(
        'https://www.passportindex.org/incl/compare2.php',
        headers={
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0',
            'Accept': '*/*',
            'Accept-Language': 'en-US,en;q=0.5',
            'Accept-Encoding': 'deflate',
            'X-Requested-With': 'XMLHttpRequest',
            'Origin': 'https://www.passportindex.org',
        },
        data={
            'compare': '3',
            'cc': str.lower(country_code),
            'year': '2024',
            'csrf_token': csrf_token
        }
    ).json()
`

**Comment by ilyankou** [comment]
From my brief experiments with Postman it seems like any _csrf_token_ would, do hence I hardcoded a dummy string. But thank you for sharing the proper way!

**Comment by ilyankou** [comment]
All fixed in the latest commit!
