### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by hrach** [ilyankou/passport-index-dataset#4]
Hi, I'd like to ask if the MIT license is really valid for the data.
I've take a look at the referenced source passportindex.org and can't see any mention about the lisence of the provided data. 

Only relevant note is

> Legal notes
> Passport Index is a free tool, built with publicly available information and with content contributed by fans and government agencies around the world. Analytics is based on proprietary research. Certain assumptions have been taken where data was missing or not reliable.

**Comment by ilyankou** [comment]
Hey Jan, 

Very good question. Passport Index folks don't seem to explicitly restrict commercial or private use, and as you pointed out they describe the data as "publicly available information" (we don't use any of their "proprietary research"), so I chose MIT to avoid this uncertainty and encourage other developers to use the data. I will happily try and work out a solution if the creators contact me about any copyright issues, but for now I don't see any reason to worry and not use the data (but giving credit is always nice!).
