### ISSUE TITLE
The data doesn't match passportindex.org

### ISSUE THREAD

**Issue by typeEquirectangular** [ilyankou/passport-index-dataset#5]
The data in the set doesn't match passportindex.org.
Take Afghanistan as an example. According to passportindex.org you have 'visa free acces' to 29 countries, while the number is 31 on in the dataset. On of the countries they differ on is Bolivia, where there is e-visa for Afghan citizens, which is listed as a 1 in data set here. Other E-visas are not written as 1 in the data set though.

I tried using the javascript to see, if this was because passportindex.org updated their data, but still got at score in the dataset of 31.

**Comment by ilyankou** [comment]
The first line in script says that data are taken from https://www.passportindex.org/comparebyPassport.php (the script doesn't fetch the data automatically). So if you ran the script without manually copy-pasting JS arrays with visa information from the source of that page to the script, you'd clearly get the same output.

I ran the script with today's data and Bolivia has a 0 for Afghanistan. I will update all 3 datasets later today.
